#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PC {
    float multiplier;
    uint buf_offset;
    uint count;
} pc;

layout(set = 0, binding = 0, std430) buffer BufData {
    float data[];
} buf;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < pc.count)
        buf.data[pc.buf_offset + i] = buf.data[pc.buf_offset + i] * pc.multiplier;
}
